### ISSUE TITLE
Using it on custom dataset

### ISSUE THREAD

**Issue by BayaCherif** [YurongYou/MODEST#2]
Did anyone use this  repo successfully on custom dataset ?

**Comment by YurongYou** [comment]
Hi BayaCheirf! Thanks for your interest! MODEST needs multiple traversals of the same scenes. If you have such data, you can follow https://github.com/YurongYou/MODEST/blob/master/data_preprocessing/lyft/LYFT_PREPROCESSING.md to similarly format your dataset.
