### ISSUE TITLE
How to generate the traversals file?

### ISSUE THREAD

**Issue by taoyanzhuce001** [YurongYou/MODEST#3]
Hi, I can't find the file 'data_preprocessing/lyft/meta_data/lyft_2019_train_sample_tracks.pkl' mentioned in 'data_preprocessing/lyft/LYFT_PREPROCESSING.md'. 
Can I generate the file using the existing code? Or I should generate it using poses myself?
Thanks!

**Comment by YurongYou** [comment]
Thanks for pointing this out! It seems I forgot to commit the .pkl's. Just uploaded them in the latest commit.
