### ISSUE TITLE
How can I run MODEST code on av2 dataset ?

### ISSUE THREAD

**Issue by Harry710887048** [YurongYou/MODEST#6]
Hello，thank you for this outstanding work！
So how can I run MODEST code on av2 datasets?

**Comment by YurongYou** [comment]
Hi Harry710887048! Thanks for your interest and sorry for late reply. As mentioned in the paper, our method makes the assumption of the availability of multiple traversals of the same location. As far as we know, the av2 dataset does not have multiple traversal data, thus our method is not applicable on the av2 dataset.
