### ISSUE TITLE
Where can I refer to the code for visualizing the results?

### ISSUE THREAD

**Issue by Truring** [YurongYou/MODEST#7]
Hello, I have completed the production of the seed label according to the ReadMe tutorial. How can I visualize these results like the images in the paper?

**Comment by Truring** [comment]
@YurongYou @katieluo88 Looking forward to your reply, thank you very much.

**Comment by YurongYou** [comment]
Hi Truring, thanks for your interest! The visualization code is not included in this codebase, and we suggest you refer to other general 3D visualization codebase for visualization (e.g. https://mmdetection3d.readthedocs.io/en/latest/user_guides/visualization.html)
